### ISSUE TITLE
issue after installaing all databases and configs ...

### ISSUE THREAD

**Issue by tabitayoub** [lowag/libremaint#11]
hello sorry to take your time i have the following message while trying to access for the first time to libremaint :

Fatal error: Uncaught Error: Undefined constant "LC_MESSAGES" in C:\xampp\htdocs\libremaint\config\lm-settings.php:42 Stack trace: #0 C:\xampp\htdocs\libremaint\includes\lm-load.php(15): require_once() #1 C:\xampp\htdocs\libremaint\includes\lm-header.php(8): include_once('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\libremaint\index.php(20): require('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\libremaint\config\lm-settings.php on line 42

please some help im on windows xamp

**Comment by lowag** [comment]
Hello,
Please replace "LC_MESSAGES" to "LC_ALL" in "C:\xampp\htdocs\libremaint\config\lm-settings.php"  line 42. Probably that fixes your problem.
