### ISSUE TITLE
What is department? Theres nothing to select

### ISSUE THREAD

**Issue by Sungjb** [lowag/libremaint#13]
<img width="780" alt="Screenshot 2024-06-25 at 17 58 24" src="https://github.com/lowag/libremaint/assets/173596303/7c937d5c-2f35-40a0-a037-007f9621f6f4">

**Comment by lowag** [comment]
Department would be the company organization where the user  work. There is a SQL table "departments" you should fill it up manually.

**Comment by Sungjb** [comment]
should i make one? I cant find it

**Comment by lowag** [comment]
There are 36 tables. One of them is departments.  In command line:  sudo mysql -p the_libremaint_database_name
Then: 
show tables;
Then:
INSERT INTO departments....
For you probably easier using PHPMyadmin or MySQL Workbench. Just to be clear: It is not a commercial software. I developed it for myself. If anybody else can use that makes me happy. It demands some nonbasic knowledge... If you need an out-of-box solution then don't waste your time. I don't think that I will have enough time for making a correct documentation.

**Comment by Sungjb** [comment]
Im sorry to give you lots of hassle, im 12 btw im still learning and helping my dad to save some money

**Comment by lowag** [comment]
a.     veres      74     at         g  m a i l    ask there
