### ISSUE TITLE
clean install - error concerning LANG2

### ISSUE THREAD

**Issue by figdot1** [lowag/libremaint#14]
complete new install. Went to Pinboard and Assets and get similar error 

Fatal error: Uncaught Error: Undefined constant "LANG2" in /home/pgtlvqlm/public_html/libremaint/pages/assets.php:106 Stack trace: #0 /home/pgtlvqlm/public_html/libremaint/pages/lm-body.php(29): require_once() #1 /home/pgtlvqlm/public_html/libremaint/index.php(30): require('/home/pgtlvqlm/...') #2 {main} thrown in /home/pgtlvqlm/public_html/libremaint/pages/assets.php on line 106

**Comment by lowag** [comment]
LANG2 should have been defined at the beginning of /home/pgtlvqlm/public_html/libremaint/config/lm-settings.php
Somehow I uncommented it.  I fixed at the branch. It should be look like this (if you use only 1 language):
define('LANG1','en');
define('LANG2','en');
Thanks

**Comment by figdot1** [comment]
Excellent. Thanks for the fix and the effort
