### ISSUE TITLE
Users - Error

### ISSUE THREAD

**Issue by figdot1** [lowag/libremaint#15]
Brand new install. Clicked on users to add new user - error 

Fatal error: Uncaught mysqli_sql_exception: Unknown column 'order_level_number' in 'field list' in /home/pgtlvqlm/public_html/libremaint/includes/MYSQL_db_class.php:85 Stack trace: #0 /home/pgtlvqlm/public_html/libremaint/includes/MYSQL_db_class.php(85): mysqli_query() #1 /home/pgtlvqlm/public_html/libremaint/pages/users.php(436): DB->select() #2 /home/pgtlvqlm/public_html/libremaint/pages/lm-body.php(28): require_once('/home/pgtlvqlm/...') #3 /home/pgtlvqlm/public_html/libremaint/index.php(30): require('/home/pgtlvqlm/...') #4 {main} thrown in /home/pgtlvqlm/public_html/libremaint/includes/MYSQL_db_class.php on line 85

**Comment by lowag** [comment]
I added a modified truncated_en_only.sql file for the start. Please try that.

**Comment by figdot1** [comment]
I have updated the SQL definitions and this error is resolved.
