### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by khan041987** [lowag/libremaint#3]
Hello,
Thanks for posting the nice applications, it seems very good, i have followed all the steps but unfortunately i am not able to login in the application. When i pass the default credential admin/admin the page is not moving to next screen it redirects back to login page without any error. Please find below errors in the log file.

```
[11-Jun-2021 22:28:52 Europe/Moscow] select * FROM users WHERE username='admin'
[11-Jun-2021 22:28:52 Europe/Moscow] PHP Notice:  Trying to access array offset on value of type null in /var/www/libremaint/includes/functions.php on line 20
[11-Jun-2021 22:28:54 Europe/Moscow] PHP Notice:  Undefined index: logged in /var/www/libremaint/pages/lm-body.php on line 4
```

Please help on this.

Thanks in advance.
Naveed.

**Comment by lowag** [comment]
Hello,
You are right, the users table of the database was empty. Fixed. 
Download the fixed truncated_en_only.sql and 
sudo mysql -p libremaint < truncated_en_only.sql
KR
Antal

**Comment by khan041987** [comment]
Hi,

I have cloned the project again and rerun the commands but still the issue same. Please guide on this.

```
[12-Jun-2021 10:37:39 Europe/Moscow] select * FROM users WHERE username='admin'
[12-Jun-2021 10:37:39 Europe/Moscow] PHP Notice:  Trying to access array offset on value of type null in /var/www/libremaint/includes/functions.php on line 20
```


Thanks,
Naveed

**Comment by khan041987** [comment]
Hi,

I have inserted the record manually no i am able to login but on main menu i can not see menus options following errors are getting recorded in the log file.


`[12-Jun-2021 11:26:03 Europe/Moscow] PHP Notice:  Undefined index: logged in /var/www/libremaint/pages/lm-body.php on line 4
[12-Jun-2021 11:26:08 Europe/Moscow] select * FROM users WHERE username='admin'
[12-Jun-2021 11:26:08 Europe/Moscow] SELECT service_interval_date,service_interval_hours,repetitive,service_interval_mileage,workrequest_id, counter_id FROM workrequests WHERE repetitive>0 AND workrequest_status=3
[12-Jun-2021 11:26:08 Europe/Moscow] SELECT Saturday_start as start,Saturday_end as end FROM users WHERE user_id=1
[12-Jun-2021 11:26:08 Europe/Moscow] PHP Warning:  Invalid argument supplied for foreach() in /var/www/libremaint/pages/dashboard.php on line 397
[12-Jun-2021 11:26:08 Europe/Moscow] PHP Warning:  Invalid argument supplied for foreach() in /var/www/libremaint/pages/dashboard.php on line 412`


Thanks,
Naveed.

**Comment by lowag** [comment]
Hi,
I suspect you are not logged in. Please check your "users" table. Or make it simpler run following SQL statements:
TRUNCATE TABLE users;
then
INSERT INTO `libremaint`.`users` (`username`,firstname,surname, `password`, `user_level`, `user_email`, `user_phone`, `user_parent_id`, `user_created`, `last_login`, `active`, `ADD_WORKORDER`, `SEE_WORKORDERS`, `SEE_WORKORDER_DETAIL`, `MODIFY_WORKORDER`, `DELETE_WORKORDER`, `ADD_FILE_TO_WORKORDER`, `SEE_FILE_OF_WORKORDER`, `SEE_CONF_FILE_OF_WORKORDER`, `DELETE_FILE_OF_WORKORDER`, `SEE_STATS_OF_WORKORDERS`, `ADD_WORK`, `SEE_WORKS`, `SEE_WORK_DETAIL`, `MODIFY_WORK`, `DELETE_WORK`, `ADD_FILE_TO_WORK`, `SEE_FILE_OF_WORK`, `SEE_CONF_FILE_OF_WORK`, `DELETE_FILE_OF_WORK`, `SEE_STATS_OF_WORKS`, `SEE_OPERATORS_WORKS`, `RECORD_OPERATOR_WORK`, `MODIFY_OPERATOR_WORK`, `DELETE_OPERATOR_WORK`, `ADD_WORKREQUEST`, `SEE_WORKREQUESTS`, `SEE_WORKREQUEST_DETAIL`, `MODIFY_WORKREQUEST`, `DELETE_WORKREQUEST`, `ADD_FILE_TO_WORKREQUEST`, `SEE_FILE_OF_WORKREQUEST`, `SEE_CONF_FILE_OF_WORKREQUEST`, `DELETE_FILE_OF_WORKREQUEST`, `SEE_STATS_OF_WORKREQUESTS`, `ADD_ASSET`, `SEE_ASSETS`, `SEE_ASSET_DETAIL`, `MODIFY_ASSET`, `DELETE_ASSET`, `ADD_FILE_TO_ASSET`, `SEE_FILE_OF_ASSET`, `SEE_CONF_FILE_OF_ASSET`, `DELETE_FILE_OF_ASSET`, `ADD_LOCATION`, `SEE_LOCATIONS`, `SEE_LOCATION_DETAIL`, `MODIFY_LOCATION`, `DELETE_LOCATION`, `ADD_FILE_TO_LOCATION`, `SEE_FILE_OF_LOCATION`, `SEE_CONF_FILE_OF_LOCATION`, `DELETE_FILE_OF_LOCATION`, `ADD_USER`, `SEE_USERS`, `SEE_USER_DETAIL`, `MODIFY_USER`, `DELETE_USER`, `ADD_FILE_TO_USER`, `SEE_FILE_OF_USER`, `SEE_CONF_FILE_OF_USER`, `DELETE_FILE_OF_USER`, `SEE_STATS_OF_USERS`, `PUT_PRODUCT_INTO_STOCK`, `TAKE_PRODUCT_FROM_STOCK`, `DELETE_PRODUCT`, `SEE_STOCK`, `STOCK-TAKING`, `SEE_PRODUCT_MOVING`, `ADD_CATEGORY`, `SEE_CATEGORY`, `MODIFY_CATEGORY`, `DELETE_CATEGORY`, `ADD_PRODUCT`, `SEE_PRODUCTS`, `SEE_PRODUCT_DETAIL`, `MODIFY_PRODUCT`, `ADD_FILE_TO_PRODUCT`, `SEE_FILE_OF_PRODUCT`, `SEE_CONF_FILE_OF_PRODUCT`, `DELETE_FILE_OF_PRODUCT`, `SEE_PRICES`, `ADD_PARTNER`, `SEE_PARTNERS`, `SEE_PARTNER_DETAIL`, `MODIFY_PARTNER`, `DELETE_PARTNER`, `SEE_FILE_OF_PARTNER`, `SEE_CONF_FILE_OF_PARTNER`, `DELETE_FILE_OF_PARTNER`, `ADD_COUNTER`, `SEE_COUNTER`, `ADD_COUNTER_VALUE`, `MODIFY_COUNTER_VALUE`, `DELETE_COUNTER`, `DELETE_COUNTER_VALUE`, `ADD_PRODUCT_WORKORDER`, `WRITE_MESSAGE`, `SEE_MESSAGE`, `CHECK_MESSAGE`, `ADD_MESSAGE_TEXT`, `ADD_FILE_TO_MESSAGE`, `SEE_FILE_OF_PRODUCT_MOVING`, `ADD_FILE_TO_PRODUCT_MOVING`, `ADD_CONNECTION_TO_ASSET`, `ADD_NEW_CONNECTION_TYPE`, `SEE_CONNECTION_TYPE`, `SEE_CONNECTION_OF_ASSET`, `SEE_CONNECTION_OF_PRODUCT`, `ADD_CONNECTION_TO_PRODUCT`, `CAN_WRITE_LANG1`, `CAN_WRITE_LANG2`, `ADD_NOTIFICATION`, `SEE_NOTIFICATIONS`, `SEE_NOTIFICATION_DETAILS`, `MODIFY_NOTIFICATION`, `DELETE_NOTIFICATION`, `SEE_STATS_OF_NOTIFICATIONS`, `users_assets`, `users_entry_points`, `telegram_chat_id`, `lang`, `Monday_start`, `Monday_end`, `Tuesday_start`, `Tuesday_end`, `Wednesday_start`, `Wednesday_end`, `Thursday_start`, `Thursday_end`, `Friday_start`, `Friday_end`, `Saturday_start`, `Saturday_end`, `Sunday_start`, `Sunday_end`, `users_card_id`) VALUES ('admin','your_firstname','your_surname', '$2y$10$HP.CoyQi6HV4U16c7u5fxu/JcI.TLtfcpGrW2S32yhh/r9OBEUGc.', '1', '', '', '0', now(),now(), b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', 'null', 'null', '0', 'en', '06:00:00.0000', '18:00:00.0000', '06:00:00.0000', '18:00:00.0000', '06:00:00.0000', '18:00:00.0000', '06:00:00.0000', '18:00:00.0000', '06:00:00.0000', '18:00:00.0000', '06:00:00.0000', '18:00:00.0000', '06:00:00.0000', '18:00:00.0000', 'null');
Antal

**Comment by khan041987** [comment]
Hi Antal,

I have tried the same before to insert the record in users table, i am logged in i can see on the right top corner admin user and even i changed the password from there and logged in after changing the password. It seems some other issue.

Thanks,
Naveed.

**Comment by lowag** [comment]
Could you check with the index.php I commited now? And please insert this line into your "libremaint/lm-settings.php":
ini_set('display_errors', 0); (avoiding to display warnings and notices)

**Comment by khan041987** [comment]
Hi,

I though some issue with my Linux Ubuntu Server i am rebuilding it, i will get back to Soon with the updates.

Thanks,
Naveed.

**Comment by khan041987** [comment]
Still the issue is same, let me attach the screen shot of the dashboard for better understanding and error logs as well. I have inserted the above suggested line as well.

![image](https://user-images.githubusercontent.com/76498142/121780607-d21d9e00-cba9-11eb-9e15-e8359e311e11.png)

Thanks,
Naveed

**Comment by lowag** [comment]
Please clone again, I have made some modifications since you had done.

**Comment by khan041987** [comment]
Hi,

I just cloned it again, now only one error please see the error details below but the menu is still not available.

```
[12-Jun-2021 19:03:00 Europe/Moscow] PHP Notice:  Undefined index: logged in /var/www/libremaint/pages/lm-body.php on line 4
[12-Jun-2021 19:03:05 Europe/Moscow] select * FROM users WHERE username='admin'
[12-Jun-2021 19:03:05 Europe/Moscow] SELECT service_interval_date,service_interval_hours,repetitive,service_interval_mileage,workrequest_id, counter_id FROM workrequests WHERE repetitive>0 AND workrequest_status=3
[12-Jun-2021 19:03:05 Europe/Moscow] SELECT Saturday_start as start,Saturday_end as end FROM users WHERE user_id=1
[12-Jun-2021 19:03:09 Europe/Moscow] SELECT Saturday_start as start,Saturday_end as end FROM users WHERE user_id=1
```

![image](https://user-images.githubusercontent.com/76498142/121782230-32640e00-cbb1-11eb-8478-fbc53a92e5c2.png)

Thanks,
Naveed.

**Comment by lowag** [comment]
if it is not working  (only for testing purpose)  modify the "includes/functions.php" at line 27
from
foreach ($priviliges as $p){
if ($p!="break" && $row[$p]==1)
$_SESSION[$p]=1;
 
} 

to

foreach ($priviliges as $p){
if ($p!="break")
$_SESSION[$p]=1;
 
}

**Comment by khan041987** [comment]
after making the above changes the page became blank.

![image](https://user-images.githubusercontent.com/76498142/121782560-c2ef1e00-cbb2-11eb-87f4-e0e5de8631fc.png)

**Comment by lowag** [comment]
Weird. You have no $_SESSION['logged']. And what about if you change includes/functions.php line 20 from
 if (password_verify($password,$row['password'])){
to
if (1){

**Comment by khan041987** [comment]
All right after putting if(1){ now i can see full menu, but the log is showing still error in lm-body.php at lione 4.

```
[12-Jun-2021 19:46:22 Europe/Moscow] PHP Notice:  Undefined index: logged in /var/www/libremaint/pages/lm-body.php on line 4
[12-Jun-2021 19:46:27 Europe/Moscow] select * FROM users WHERE username='admin'
[12-Jun-2021 19:46:27 Europe/Moscow] SELECT service_interval_date,service_interval_hours,repetitive,service_interval_mileage,workrequest_id, counter_id FROM workrequests WHERE repetitive>0 AND workrequest_status=3
[12-Jun-2021 19:46:27 Europe/Moscow] SELECT Saturday_start as start,Saturday_end as end FROM users WHERE user_id=1
```

**Comment by lowag** [comment]
That is just a notice. 
THX, I truncated it also. For "user_levels" table I using: 
INSERT INTO `user_levels` VALUES (1,'system admin','rendszeradminisztrátor'),(2,'manager','vezető'),(3,'technician','karbantartó'),(4,'operator','gépkezelő'),(5,'technologist','technológus');
After it you should try to add another 'system admin' and then to make the code back to original.

**Comment by khan041987** [comment]
All right i was just going through the menus and seeing in the logs it is throwing errors on different pages. Anyway i will go through and will revert back in case if need help. Should i leave the changes as you have advised in previous post in function file? Also on user form it is showing error

![image](https://user-images.githubusercontent.com/76498142/121783879-e073b600-cbb9-11eb-92a6-cf1823ec9df7.png)


Thanks for the help and support.
Naveed.

**Comment by lowag** [comment]
If your user_levels table is not empty, there must a 'user_level_en' field. Check in config/lm-settings.php the
$lang = 'en'; variable 
if it is, then try to repeat it at the bottom of that file.
"Report to" is boss of that employee. The boss can order only the employees belong under her/him.

**Comment by khan041987** [comment]
Reports to belongs to which table in database so that i can try to enter some records to database? And what i believe is there should be a forms to enter the user levels and reporting line.

**Comment by lowag** [comment]
You should start with the big boss and then go ahead from level to level. "report to" is a simple user in the users table. Every users can have a "user_parent_id" (whom she/he report to).

**Comment by khan041987** [comment]
Ok let me check on this and what about the front end forms for user levels entry and reports to entry?

Thanks for the help.
I took your a lot of time let me go through the module and will let you know the feedback.

**Comment by lowag** [comment]
There is no front end for user levels. Rarely need to be changed .

**Comment by khan041987** [comment]
Ok perfect i am checking it, can i ask you one more question. How to control the user access i have created one technician user it has full access. Can you please clarify this.

**Comment by lowag** [comment]
On the users page you can click on the "person" icon next to row number.

**Comment by khan041987** [comment]
I did that i tried checking few to see if the rights gets apply but user has full rights then i tried all check boxes still the user has full rights it seems no control. i think there is some issue.

**Comment by lowag** [comment]
The changes take effect only from the next login.

**Comment by khan041987** [comment]
Even i tried that one as well still the level 3 user has full rights let me get some details from database i will post it here.

**Comment by khan041987** [comment]
See this is the output from database which seems the technician user also have same rights as admin by default.

mysql> select username,user_level,ADD_WORKORDER from users;
+----------+------------+------------------------------+
| username | user_level | ADD_WORKORDER                |
+----------+------------+------------------------------+
| admin    |          1 | 0x00                         |
| salem    |          3 | 0x00                         |
+----------+------------+------------------------------+

**Comment by lowag** [comment]
Oh. It is because you changed the functions.php.  I commited some changes now. You should try again.

**Comment by khan041987** [comment]
Should i only copy functions file?

**Comment by lowag** [comment]
the functions.php is enough.

**Comment by khan041987** [comment]
All right let me try.

**Comment by khan041987** [comment]
Again same issue menu disappeared after replacing the function file. And no errors in the log file.

**Comment by lowag** [comment]
Is that true for the other user too?

**Comment by khan041987** [comment]
Yes both users showing same behavior now no menu same like before.

**Comment by lowag** [comment]
could you give me the output of
php --version
mysql --version

**Comment by khan041987** [comment]
```
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```
`mysql  Ver 8.0.25-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))`

**Comment by lowag** [comment]
You are using newer versions than me, but it should not be a problem. Could you send me your /etc/php/7.4/apache2/php.ini I would check it tomorrow. betabagoly@g m a i l . c o m

**Comment by khan041987** [comment]
Sure i will do that.

Thanks.

**Comment by khan041987** [comment]
I have sent you the php.ini file.

Thanks,
Naveed.
